### ISSUE TITLE
Inline code snippets not working

### ISSUE THREAD

**Issue by cfaddict** [EldoranDev/gridsome-plugin-remark-shiki#1]
Is there a way to allow inline code snippets and not create a whole block for it? I have the following text in markdown

`In this article, I am going to take a look at the ``&lt;template&gt;`` tag `

and it's causing an error and won't display anything past it. 

![2019-02-13_22-14-36](https://user-images.githubusercontent.com/349507/52760244-dc7cfc80-2fdc-11e9-8e4c-0a46d43a285b.png)

**Comment by EldoranDev** [comment]
@cfaddict what would be the expected behaviour for you ? (beside that the code actually shows up).
I agree with you that like inline code should not trigger a complete line there.

Did you try it with single ` ? 

I'll look into this problem maybe later today or tomorrow.

**Comment by cfaddict** [comment]
If know that I have done that in gitbook but I will have to test out if the same happens in VuePress or not. Sorry it was just a single backtick, I was trying to escape it here on Github.

**Comment by EldoranDev** [comment]
Latest dev branch (available on npm with the `@dev` tag should fix the issue if you want to take a look at it.

I'll test some more and promote it to @latest if it works.

**Comment by cfaddict** [comment]
Thank you!

**Comment by cfaddict** [comment]
I updated to @dev ("gridsome-plugin-remark-shiki": "^0.1.1",) and I am still seeing the issue. This is the text in question: 

This might be an area that folks have some trouble upgrading because of the security model changes which we will talk about those in a few. By default, all web endpoints are available beneath the path  `/actuator`  with URLs of the form  `/actuator/{id}` . The  `/actuator`  base path can be configured by using the  `management.endpoints.web.base-path`  property. There is a [dedicated detailed document for Spring Boot Actuator Web API Endpoints](https://docs.spring.io/spring-boot/docs/2.0.x/actuator-api/html/) and this is a great place to start. 

It's showing up now but still triggering a new line.  

![2019-02-17_11-22-43](https://user-images.githubusercontent.com/349507/52915833-92c73700-32a6-11e9-97d0-39a1472d7f3d.png)

**Comment by EldoranDev** [comment]
Are the inline blocks rendering as `code` tags ? Do you have some specific styles for `code` or `.shiki` ?

I could change the inline blocks to render as `<code class="shiki-inline">` instead of `<code class="shiki">`

**Comment by cfaddict** [comment]
Yes I think that would work. I went in and added that around the the template tag and it worked..

`<code class="shiki-inline">&lt;template&gt;</code> `

![2019-02-20_20-16-53](https://user-images.githubusercontent.com/349507/53136305-8106bd80-354c-11e9-861f-c9adda398598.png)

**Comment by hellocosmin** [comment]
The plugin is still `0.1.0` on NPM, so inline `code` is still being wrapped with `<pre>` instead of `<code>`, which makes it impossible to style differently. Can you please update that? Thanks for creating this 👍

**Comment by EldoranDev** [comment]
Oh my bad, missed the failing travis deploy for 0.1.3

just published it as 0.2.0.

**Comment by hellocosmin** [comment]
Thank you! 😊
